import Header from "@/components/Header"
import "../../styles/globals.css"
import Banner from "@/components/Banner"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      {/* header */}
            {/* banner */}

      <body className="max-w-7xl mx-auto">
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  )
}
